version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: monitoring_nginx
    ports:
      - "8030:80"
    volumes:
      - ./tools/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  node-exporter:
    image: prom/node-exporter:1.6.1
    container_name: monitoring_node_exporter
    ports:
      - "9100"
    restart: unless-stopped

  app:
    depends_on:
      - app
      - alertmanager
      - nginx_exporter
      - node-exporter

  nginx_exporter:
    depends_on:
      - nginx