version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: monitoring_nginx
    ports:
      - "8030:80"
    volumes:
      - ./tools/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  nginx_exporter:
    depends_on:
      - nginx