version: '3.8'
services:

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    container_name: monitoring_nginx_exporter
    command: ["-nginx.scrape-uri", "${NGINX_SCRAPE_URL}"]

  app:
    build: .
    container_name: monitoring_app
    ports:
      - "3000:3000"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: monitoring_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
      - ./prometheus/file_sd:/etc/prometheus/file_sd:ro
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - app
      - alertmanager
      - nginx_exporter

  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: monitoring_alertmanager
    ports:
      - "9093:9093"
    restart: unless-stopped
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/config.yml:ro
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    depends_on:
      - am-telegram

  am-telegram:
    build: ./tools/am-telegram
    container_name: monitoring_am_telegram
    ports:
      - "9094:9094"
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}

  grafana:
    image: grafana/grafana:9.5.0
    container_name: monitoring_grafana
    ports:
      - "3001:3000"
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    depends_on:
      - prometheus

  opensearch:
    image: opensearchproject/opensearch:2.8.0
    container_name: monitoring_opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    restart: unless-stopped
    depends_on:
      - app

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.8.0
    container_name: monitoring_opensearch_dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
    restart: unless-stopped
    depends_on:
      - opensearch

volumes:
  grafana-storage:
  opensearch-data:
