global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/alert.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'monitoring-app'
    static_configs:
      - targets: []
        labels:
          service: 'monitoring-app'
    file_sd_configs:
      - files:
          - /etc/prometheus/file_sd/app_targets.yml
    relabel_configs:
      - source_labels: [__address__]
        regex: "(.*)"
        target_label: instance
        replacement: "$1"

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: []
        labels:
          service: 'node-exporter'
    file_sd_configs:
      - files:
          - /etc/prometheus/file_sd/node_exporter_targets.yml
    relabel_configs:
      - source_labels: [__address__]
        regex: "(.*)"
        target_label: instance
        replacement: "$1"

  - job_name: 'nginx_exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['nginx_exporter:9113']
        labels:
          service: 'nginx'
