global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/alert.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'monitoring-app'
    static_configs:
      - targets: ['${APP_HOST}']
        labels:
          service: 'monitoring-app'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['${NODE_EXPORTER_HOST}']
        labels:
          service: 'node-exporter'

  - job_name: 'nginx_exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['nginx_exporter:9113']
        labels:
          service: 'nginx'
